In [1]:
from models.composer.generate import RNNGenerator
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import array_ops

configs = {
    'model_path': '/home/richhiey/Desktop/workspace/projects/virtual_musicians/cache/test_model5',
    'vocab_size': 389,
    'emb_size': 128,
    'lstm_units': 512,
    'dense_units': 64,
    'max_timesteps': 256,
    'rnn': {'num_units': 512, 'num_layers': 1, 'unit_type': 'lstm'},
}

g = RNNGenerator(configs)

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(16, 256)]               0         
_________________________________________________________________
embedding (Embedding)        (16, 256, 128)            49792     
_________________________________________________________________
rnn (RNN)                    (16, 256, 512)            1312768   
_________________________________________________________________
dense (Dense)                (16, 256, 389)            199557    
Total params: 1,562,117
Trainable params: 1,562,117
Non-trainable params: 0
_________________________________________________________________
Initializing from scratch.


In [ ]:
DATA_PATH = '/home/richhiey/Desktop/workspace/projects/virtual_musicians/data-store/POP909-Dataset/data_process/pop909-event-token.npy'
data = np.load(DATA_PATH, allow_pickle=True)
print(len(data))
melodies = [d['MELODY'] for d in data]

def generator_fn():
    for melody in melodies:
        yield tf.convert_to_tensor([melody])

dataset = tf.data.Dataset.from_generator(generator_fn, tf.int64, tf.TensorShape([1, None]))

for data in dataset:
    x = data
    print(x)
    print(x.numpy())
    break

boundaries = [128 * (i+1) for i in range(20)]
batch_sizes = [16] * (len(boundaries) + 1)

def _element_length_fn(x, y=None):
    return array_ops.shape(x)[1]

dataset = dataset.apply(
    tf.data.experimental.bucket_by_sequence_length(
        _element_length_fn,
        boundaries,
        batch_sizes,
        drop_remainder=True,
        pad_to_bucket_boundary=False
    )
)

print(dataset)
for x in dataset:
    print(x)
    break
    

g.train(dataset, {'num_epochs':1, 'print_every': 3, 'save_every': 1000,})

909
tf.Tensor([[355 355 355 ...  73 291 201]], shape=(1, 2221), dtype=int64)
[[355 355 355 ...  73 291 201]]
<_GroupByWindowDataset shapes: (None, 1, None), types: tf.int64>
tf.Tensor(
[[[355 355 355 ...   0   0   0]]

 [[355 355 355 ...   0   0   0]]

 [[355 355 355 ...   0   0   0]]

 ...

 [[355 355 355 ...   0   0   0]]

 [[355 355 355 ... 355 337 209]]

 [[355 355 355 ...   0   0   0]]], shape=(16, 1, 1533), dtype=int64)
tf.Tensor([  16    1 1533], shape=(3,), dtype=int32)
tf.Tensor(5.963598, shape=(), dtype=float32)
tf.Tensor(5.963598, shape=(), dtype=float32)
tf.Tensor(5.963598, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
tf.Tensor(5.963597, shape=(), dtype=float32)
Loss: 5.9635973
tf.Ten

tf.Tensor(5.9635396, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 384 384 384 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[378  75 351 203 378  68 278 196 373  68 278 375  68 196 278 372  68 196
 279 196 380  75 302 203 378  75 279 380  73 203 303 201 377  73 278 201
 378  73 278 201 386  78 302 385  78 206 278 386  78 206 279 206 381  78
 278 206 380  73 303 378  73 201 278 382  73 201 279 201 374  75 302 203
 373  75 278 374  72 203 303 200 375  72 278 200 378  72 278 200 378  68
 279 380  68 196 355 3

tf.Tensor(5.9635196, shape=(), dtype=float32)
tf.Tensor(5.963541, shape=(), dtype=float32)
tf.Tensor(5.963541, shape=(), dtype=float32)
tf.Tensor(5.9635396, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963535, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.9635396, shape=(), dtype=float32)
Loss: 5.963536
tf.Tensor([  16    1 1919], shape=(3,), dtype=int32)
tf.Tensor(5.9634867, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.963536, shape=(), dtype=float32)
tf.Tensor(5.9635205, shape=(), dtype=float32)
tf.Tensor(5.9635196, shape=(), dtype=float32)
tf.Tensor(5.9635196, shape=(), dtype=float32)
tf.Tensor(5.963535, shape=(), dtype=float32)
tf.Tensor(5.9635205, shape=(), dtype=float32)
tf.Tensor(5.9635205, sha

tf.Tensor(5.9634852, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[ 67 355 355 259 195 355 355 257 378  67 270 195 260 378  67 266 195 265
 379  67 272 195 258 380  74 284 202 268 382  74 270 202 260 380  72 270
 200 261 380  72 321 200 295 380  70 275 198 382  72 267 200 264 380  74
 274 202 256 381  67 284 195 268 380  67 270 195 260 381  65 271 193 260
 380  67 283 195 269 381  67 353 195 355 291 380  67 267 195 264 379  67
 266 195 264 380  67 2

tf.Tensor(5.963466, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[ 79 355 274 207 328 382  79 288 207 264 381  77 273 205 257 382  77 267
 205 264 381  74 271 202 259 381  81 288 209 264 380  81 267 209 263 382
  81 283 209 269 381  77 269 205 262 381  77 266 205 264 382  74 343 202
 316 380  72 276 383  70 200 265 198 265 381  72 267 200 263 380  74 264
 202 267 381  67 330 195 307 380  72 289 200 263 382  74 266 202 265 380
  65 293 193 258 379  7

tf.Tensor(5.8850107, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[ 67 293 195 260 385  71 302 199 273  69 295 197 258 380  71 270 199 261
  62 324 190 273 378  62 269 190 262 381  71 293 199 261 376  69 266 197
 265 381  69 355 306 197 355 289 386  71 282 199 272 379  69 284 197 269
 385  71 280 199 273 380  69 265 197 266 388  71 314 199 349 381  67 276
 195 380  66 269 194 262 382  66 290 194 263 384  74 287 202 267 386  74
 285 202 268 384  76 2

tf.Tensor(5.919277, shape=(), dtype=float32)
tf.Tensor(5.923203, shape=(), dtype=float32)
tf.Tensor(5.936991, shape=(), dtype=float32)
tf.Tensor(5.9266505, shape=(), dtype=float32)
Loss: 5.9103465
tf.Tensor([  16    1 1786], shape=(3,), dtype=int32)
tf.Tensor(5.828454, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 257 377  71 268 199 259
 378  73 267 201 260 378  75 355 280 203 272 379  73 296 201 266 

tf.Tensor(5.9325347, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[267 377  71 301 199 261 378  70 287 198 258 376  71 355 280 199 355 297
 375  66 266 194 261 377  71 275 199 269 376  71 272 199 273 377  71 275
 199 270  71 272 199 256 377  70 279 198 282 377  70 282 198 263 378  68
 290 196 377  70 326 376  66 198 355 267 194 355 378  71 267 199 260 378
  73 265 201 262 378  75 355 280 203 272 377  78 300 206 262 377  73 301
 201 262  75 312 203 2

tf.Tensor(5.8917055, shape=(), dtype=float32)
tf.Tensor(5.936502, shape=(), dtype=float32)
tf.Tensor(5.9453197, shape=(), dtype=float32)
tf.Tensor(5.9443417, shape=(), dtype=float32)
tf.Tensor(5.916775, shape=(), dtype=float32)
tf.Tensor(5.952236, shape=(), dtype=float32)
tf.Tensor(5.94631, shape=(), dtype=float32)
Loss: 5.928832
tf.Tensor([  16    1 1399], shape=(3,), dtype=int32)
tf.Tensor(5.8055253, shape=(), dtype=float32)
tf.Tensor(
[355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355 355
 355], shape=(127,), dtype=int64)
tf.Tensor(
[3