In [1]:
import tensorflow as tf
import numpy as np

from models.composer.translate import TransformerTranslator
from data.preprocess import load_POP909_dataset_translator

In [2]:
DATA_PATH = 'data/pop909-event-token.npy'
BATCH_SIZE = 2
data = np.load(DATA_PATH, allow_pickle=True)
print(data[0].keys())
dataset = load_POP909_dataset_translator(DATA_PATH, 'MELODY', 'PIANO', BATCH_SIZE)

print(dataset)
for x in dataset:
    print(x)
    break

dict_keys(['MELODY', 'BRIDGE', 'PIANO'])
<ShuffleDataset shapes: ((None, 1, None), (None, 1, None)), types: (tf.int64, tf.int64)>
(<tf.Tensor: shape=(2, 1, 1689), dtype=int64, numpy=
array([[[355, 355, 355, ...,   0,   0,   0]],

       [[355, 355, 355, ..., 355, 323, 193]]])>, <tf.Tensor: shape=(2, 1, 5504), dtype=int64, numpy=
array([[[355, 355, 290, ..., 193, 256, 190]],

       [[355, 355, 280, ...,   0,   0,   0]]])>)


In [4]:
configs = {
    'model_path': '../cache/checkpoints/test_model',
    'num_layers': 2,
    'd_model': 256,
    'num_heads': 4,
    'dff': 512,
    'input_vocab_size': 389,
    'target_vocab_size': 389,
    'pe_input': 128,
    'pe_target': 128
}
translator = TransformerTranslator(configs)
translator.train(dataset, {'num_epochs': 100, 'print_every': 100, 'save_every': 1000,})

Initializing from scratch.
tf.Tensor([   2    1 1483], shape=(3,), dtype=int32)
tf.Tensor([   2    1 5504], shape=(3,), dtype=int32)
tf.Tensor(6.499068, shape=(), dtype=float32)
tf.Tensor(6.454043, shape=(), dtype=float32)
tf.Tensor(6.4380875, shape=(), dtype=float32)
tf.Tensor(6.3698425, shape=(), dtype=float32)
tf.Tensor(6.4499197, shape=(), dtype=float32)
tf.Tensor(6.364502, shape=(), dtype=float32)
tf.Tensor(6.3632336, shape=(), dtype=float32)
tf.Tensor(6.4565926, shape=(), dtype=float32)
tf.Tensor(6.3814588, shape=(), dtype=float32)
tf.Tensor(6.4039, shape=(), dtype=float32)
tf.Tensor(6.448034, shape=(), dtype=float32)
Loss: 6.420789
tf.Tensor([   2    1 2001], shape=(3,), dtype=int32)
tf.Tensor([   2    1 4886], shape=(3,), dtype=int32)
tf.Tensor(6.3981333, shape=(), dtype=float32)
tf.Tensor(6.4829197, shape=(), dtype=float32)
tf.Tensor(6.52368, shape=(), dtype=float32)
tf.Tensor(6.421664, shape=(), dtype=float32)
tf.Tensor(6.4082284, shape=(), dtype=float32)
tf.Tensor(6.345257, 

tf.Tensor(5.180994, shape=(), dtype=float32)
tf.Tensor(5.1045847, shape=(), dtype=float32)
tf.Tensor(4.982377, shape=(), dtype=float32)
tf.Tensor(5.024789, shape=(), dtype=float32)
tf.Tensor(4.9530125, shape=(), dtype=float32)
tf.Tensor(4.7850385, shape=(), dtype=float32)
tf.Tensor(4.943084, shape=(), dtype=float32)
tf.Tensor(4.889039, shape=(), dtype=float32)
tf.Tensor(4.802349, shape=(), dtype=float32)
tf.Tensor(4.899225, shape=(), dtype=float32)
Loss: 4.9954243
tf.Tensor([   2    1 1557], shape=(3,), dtype=int32)
tf.Tensor([   2    1 4501], shape=(3,), dtype=int32)
tf.Tensor(5.1097126, shape=(), dtype=float32)
tf.Tensor(5.022903, shape=(), dtype=float32)
tf.Tensor(5.1706915, shape=(), dtype=float32)
tf.Tensor(5.1010537, shape=(), dtype=float32)
tf.Tensor(5.0846667, shape=(), dtype=float32)
tf.Tensor(4.944805, shape=(), dtype=float32)
tf.Tensor(4.9416256, shape=(), dtype=float32)
tf.Tensor(4.937664, shape=(), dtype=float32)
tf.Tensor(4.8804417, shape=(), dtype=float32)
tf.Tensor(4.79

tf.Tensor(1.1571945, shape=(), dtype=float32)
Loss: 1.4173653
tf.Tensor([   2    1 1489], shape=(3,), dtype=int32)
tf.Tensor([   2    1 4595], shape=(3,), dtype=int32)
tf.Tensor(1.4179409, shape=(), dtype=float32)
tf.Tensor(1.0942941, shape=(), dtype=float32)
tf.Tensor(1.0029542, shape=(), dtype=float32)
tf.Tensor(1.2344929, shape=(), dtype=float32)
tf.Tensor(1.3336554, shape=(), dtype=float32)
tf.Tensor(1.2174033, shape=(), dtype=float32)
tf.Tensor(1.0728221, shape=(), dtype=float32)
tf.Tensor(0.80985117, shape=(), dtype=float32)
tf.Tensor(0.8523216, shape=(), dtype=float32)
tf.Tensor(0.83060545, shape=(), dtype=float32)
tf.Tensor(0.84705, shape=(), dtype=float32)
Loss: 1.0648538
tf.Tensor([   2    1 1648], shape=(3,), dtype=int32)
tf.Tensor([   2    1 4958], shape=(3,), dtype=int32)
tf.Tensor(1.0775783, shape=(), dtype=float32)
tf.Tensor(0.9741348, shape=(), dtype=float32)
tf.Tensor(0.9336835, shape=(), dtype=float32)
tf.Tensor(0.8211937, shape=(), dtype=float32)
tf.Tensor(1.0315601,

tf.Tensor(0.28428784, shape=(), dtype=float32)
tf.Tensor(0.18631332, shape=(), dtype=float32)
tf.Tensor(0.16250706, shape=(), dtype=float32)
tf.Tensor(0.20879461, shape=(), dtype=float32)
tf.Tensor(0.16144413, shape=(), dtype=float32)
tf.Tensor(0.21743988, shape=(), dtype=float32)
tf.Tensor(0.15875712, shape=(), dtype=float32)
tf.Tensor(0.14224379, shape=(), dtype=float32)
tf.Tensor(0.18147993, shape=(), dtype=float32)
tf.Tensor(0.14964086, shape=(), dtype=float32)
tf.Tensor(0.12904327, shape=(), dtype=float32)
Loss: 0.18017744
tf.Tensor([   2    1 1738], shape=(3,), dtype=int32)
tf.Tensor([   2    1 4534], shape=(3,), dtype=int32)
tf.Tensor(0.6217046, shape=(), dtype=float32)
tf.Tensor(0.6461679, shape=(), dtype=float32)
tf.Tensor(0.57975465, shape=(), dtype=float32)
tf.Tensor(0.42843035, shape=(), dtype=float32)
tf.Tensor(0.5604842, shape=(), dtype=float32)
tf.Tensor(0.6274606, shape=(), dtype=float32)
tf.Tensor(0.6049923, shape=(), dtype=float32)
tf.Tensor(0.72058016, shape=(), dtyp

tf.Tensor(0.06939021, shape=(), dtype=float32)
Loss: 0.077389404
tf.Tensor([   2    1 2224], shape=(3,), dtype=int32)
tf.Tensor([   2    1 5553], shape=(3,), dtype=int32)
tf.Tensor(0.17745957, shape=(), dtype=float32)
tf.Tensor(0.0717642, shape=(), dtype=float32)
tf.Tensor(0.12836821, shape=(), dtype=float32)
tf.Tensor(0.10354662, shape=(), dtype=float32)
tf.Tensor(0.16821514, shape=(), dtype=float32)
tf.Tensor(0.07772472, shape=(), dtype=float32)
tf.Tensor(0.07773948, shape=(), dtype=float32)
tf.Tensor(0.10623055, shape=(), dtype=float32)
tf.Tensor(0.08447655, shape=(), dtype=float32)
tf.Tensor(0.08003709, shape=(), dtype=float32)
tf.Tensor(0.073968425, shape=(), dtype=float32)
tf.Tensor(0.08674931, shape=(), dtype=float32)
tf.Tensor(0.10303869, shape=(), dtype=float32)
tf.Tensor(0.14431742, shape=(), dtype=float32)
tf.Tensor(0.13185617, shape=(), dtype=float32)
tf.Tensor(0.11783424, shape=(), dtype=float32)
tf.Tensor(0.11453845, shape=(), dtype=float32)
Loss: 0.108697936
tf.Tensor([ 

KeyboardInterrupt: 