In [4]:
import tensorflow as tf
import numpy as np

from models.composer.translate import TransformerTranslator
from data.preprocess import load_POP909_dataset_translator

In [5]:
DATA_PATH = 'data/pop909-event-token.npy'
BATCH_SIZE = 2
data = np.load(DATA_PATH, allow_pickle=True)
print(data[0].keys())
dataset = load_POP909_dataset_translator(DATA_PATH, 'MELODY', 'PIANO', BATCH_SIZE)

print(dataset)
for x in dataset:
    print(x)
    break

dict_keys(['MELODY', 'BRIDGE', 'PIANO'])
<ShuffleDataset shapes: ((None, 1, None), (None, 1, None)), types: (tf.int64, tf.int64)>
(<tf.Tensor: shape=(2, 1, 1778), dtype=int64, numpy=
array([[[355, 355, 355, ...,  79, 316, 207]],

       [[355, 355, 355, ...,   0,   0,   0]]])>, <tf.Tensor: shape=(2, 1, 5654), dtype=int64, numpy=
array([[[355, 355, 355, ...,   0,   0,   0]],

       [[299, 377,  47, ..., 175, 257, 163]]])>)


In [6]:
configs = {
    'model_path': '../cache/checkpoints/test_model',
    'num_layers': 2,
    'd_model': 256,
    'num_heads': 4,
    'dff': 512,
    'input_vocab_size': 389,
    'target_vocab_size': 389,
    'pe_input': 128,
    'pe_target': 128
}
translator = TransformerTranslator(configs)
translator.train(dataset, {'num_epochs': 100})

Initializing from scratch.


InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [2,1,2158] != values[1].shape = [2,1,4767] [Op:Pack] name: packed